sjobs:
  - { git_repo_url: https://github.com/akr9757/roboshop-terraform.git, job_name: roboshop-terraform}
  - { git_repo_url: https://github.com/akr9757/roboshop-ansible.git, job_name: roboshop-ansible}
  - { git_repo_url: https://github.com/akr9757/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store}

mjobs:
  - { git_repo_url: https://github.com/akr9757/cart.git, job_name: cart}
